// Generated by CoffeeScript 1.9.3
(function() {
  var Bucketlist;

  Bucketlist = new Backbone.Collection.extend({
    model: Goal,
    initialize: function() {
      this.set('goalCount', this.getGoalCount());
      this.set('goalsAccomplishedCount', this.getGoalsAccomplishedCount());
      if (!window.localStorage.getItem('myBucketlist')) {
        window.localStorage.setItem('myBucketlist', JSON.stringify(this));
      }
      return this.on('add', function() {
        window.localStorage.setItem('myBucketlist', JSON.stringify(this));
      });
    },
    getGoalCount: function() {},
    getGoalsAccomplishedCount: function() {}
  });

}).call(this);

//# sourceMappingURL=bucketlist.js.map
