// Generated by CoffeeScript 1.9.3
(function() {
  var AppView;

  AppView = Backbone.View.extend({
    $el: $('#app'),
    initialize: function() {
      return this.on('click #add-goal', this.displayGoalPrompt);
    },
    displayGoalPrompt: function() {}
  });

}).call(this);

//# sourceMappingURL=appView.js.map
