// Generated by CoffeeScript 1.9.3
(function() {
  var BucketlistView;

  BucketlistView = new Backbone.View.extend({
    events: {
      'event': 'event handler'
    },
    template: function() {},
    render: function() {}
  });

}).call(this);

//# sourceMappingURL=bucketlistView.js.map
