// Generated by CoffeeScript 1.9.3
(function() {
  var Goal;

  Goal = new Backbone.Model.extend({
    initialize: function() {},
    defaults: {
      goal: 'No goal provided',
      due_date: new Date,
      notes: '',
      photos: '',
      categories: [],
      "private": false,
      accomplished: false
    }
  });

}).call(this);

//# sourceMappingURL=goal.js.map
