// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.Goal = (function(superClass) {
    extend(Goal, superClass);

    function Goal() {
      return Goal.__super__.constructor.apply(this, arguments);
    }

    Goal.prototype.initialize = function() {};

    Goal.prototype.defaults = {
      goal: 'No goal provided',
      due_date: new Date,
      notes: '',
      photos: '',
      categories: [],
      "private": false,
      accomplished: false
    };

    return Goal;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=goal.js.map
