// Generated by CoffeeScript 1.9.3
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

window.BucketlistView = (function(superClass) {
  extend(BucketlistView, superClass);

  function BucketlistView() {
    return BucketlistView.__super__.constructor.apply(this, arguments);
  }

  BucketlistView.prototype.events = {
    'event': 'event handler'
  };

  BucketlistView.prototype.template = function() {};

  BucketlistView.prototype.render = function() {};

  return BucketlistView;

})(Backbone.View);
